name: Pull Request Build

on:
  pull_request:
    branches: 
    - dev
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore ./src/ChatterBot.sln
    
    - name: Build
      run: dotnet build ./src/ChatterBot.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ./src/ChatterBot.sln --configuration Release --no-build --verbosity normal
